steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/poepublic-shareabouts/shareabouts-pbboston', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/poepublic-shareabouts/shareabouts-pbboston']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/poepublic-shareabouts/shareabouts-pbboston', '--region', 'us-central1']

images:
  - gcr.io/poepublic-shareabouts/shareabouts-pbboston